const fs = require('fs');
const path = require('path');

// Try to load dotenv, but don't fail if .env doesn't exist
try {
  require('dotenv').config();
} catch (e) {
  // dotenv not available or .env doesn't exist - that's okay
}

// Check if we're in production mode
// This can be set via NODE_ENV environment variable or command line
const env = process.env.NODE_ENV || 'development';
const isProduction = env === 'production' || process.argv.includes('--production');

// Get environment variables (from process.env - works in Render)
const googleApiKey = process.env.GOOGLE_API_KEY || '';
const apiUrl = process.env.API_URL || (isProduction ? '' : 'http://localhost:3000/api');

// Always create the file, even if API key is empty
const environmentContent = `// This file is auto-generated by scripts/set-env.js
// DO NOT edit this file directly - it will be overwritten
// Set your environment variables in .env file or Render dashboard
export const environment = {
  production: ${isProduction},
  googleApiKey: '${googleApiKey.replace(/'/g, "\\'").replace(/\\/g, "\\\\")}',
  apiUrl: '${apiUrl.replace(/'/g, "\\'").replace(/\\/g, "\\\\")}'
};
`;

// Get absolute path to ensure we're writing to the right location
const scriptDir = __dirname;
const projectRoot = path.resolve(scriptDir, '..');
const envPath = path.join(projectRoot, 'src', 'environments', 'environment.ts');

// Ensure the directory exists
const envDir = path.dirname(envPath);
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
  console.log(`✓ Created directory: ${envDir}`);
}

// Write the file
try {
  fs.writeFileSync(envPath, environmentContent, 'utf8');
  console.log(`✓ Environment file generated for ${env} mode`);
  console.log(`✓ Environment file written to: ${envPath}`);
  
  if (googleApiKey) {
    const maskedKey = googleApiKey.length > 14 
      ? `${googleApiKey.substring(0, 10)}...${googleApiKey.substring(googleApiKey.length - 4)}`
      : '***';
    console.log(`✓ GOOGLE_API_KEY: ${maskedKey}`);
  } else {
    console.log(`⚠ GOOGLE_API_KEY: Not set (will use empty string)`);
  }
} catch (error) {
  console.error('✗ Error writing environment file:', error);
  process.exit(1);
}