const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Check if we're in production mode
// This can be set via NODE_ENV environment variable or command line
const env = process.env.NODE_ENV || 'development';
const isProduction = env === 'production' || process.argv.includes('--production');

// Get environment variables
const googleApiKey = process.env.GOOGLE_API_KEY || '';
const apiUrl = process.env.API_URL || (isProduction ? '' : 'http://localhost:3000/api');

// Warn if API key is missing (unless in production where it might be set in Render)
if (!googleApiKey && !isProduction) {
  console.warn('⚠️  WARNING: GOOGLE_API_KEY is not set!');
  console.warn('   Please create a .env file in the root directory with:');
  console.warn('   GOOGLE_API_KEY=your_api_key_here');
  console.warn('');
}

const environmentContent = `// This file is auto-generated by scripts/set-env.js
// DO NOT edit this file directly - it will be overwritten
// Set your environment variables in .env file or Render dashboard
export const environment = {
  production: ${isProduction},
  googleApiKey: '${googleApiKey.replace(/'/g, "\\'")}',
  apiUrl: '${apiUrl.replace(/'/g, "\\'")}'
};
`;

const envPath = path.join(__dirname, '../src/environments/environment.ts');

// Ensure the directory exists
const envDir = path.dirname(envPath);
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

fs.writeFileSync(envPath, environmentContent, 'utf8');
console.log(`✓ Environment file generated for ${env} mode`);
if (googleApiKey) {
  console.log(`✓ GOOGLE_API_KEY: ${googleApiKey.substring(0, 10)}...${googleApiKey.substring(googleApiKey.length - 4)}`);
} else {
  console.log(`✗ GOOGLE_API_KEY: Not set`);
}
console.log(`✓ Environment file written to: ${envPath}`);

